name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update repo on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 185.39.79.89
          username: beka
          key: ${{ secrets.DASHBOARD_SERVER_KEY }}
          port: 22
          script: |
            # Navigate to the directory where the repo is to be cloned
            cd /var/www/

            # Remove the old directory if it exists
            sudo rm -rf skynetEmployeeBonuses

            # Clone the repository
            sudo git clone https://github.com/bekachino/skynetEmployeeBonuses.git

            # Navigate into the repo
            cd skynetEmployeeBonuses

            # Install dependencies and build
            npm install
            npm run build

      - name: Restart nginx
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 185.39.79.89
          username: beka
          password: ${{ secrets.DASHBOARD_SERVER_PASSWORD }}
          key: ${{ secrets.DASHBOARD_SERVER_KEY }}
          port: 22
          script: |
            sudo service nginx restart
