name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy via scp
        uses: appleboy/scp-action@v0.1.7
        with:
          debug: true
          host: 185.39.79.89
          username: beka
          key: ${{ secrets.DASHBOARD_SERVER_KEY }}
          port: 22
          source: ./build/*
          target: /var/www/bonuses

      - name: Restart nginx
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 185.39.79.89
          username: beka
          key: ${{ secrets.DASHBOARD_SERVER_KEY }}
          port: 22
          script: sudo service nginx restart