name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update repo
        uses: appleboy/scp-action@v0.1.7
        with:
          debug: true
          host: 185.39.79.89
          username: beka
          key: ${{ secrets.DASHBOARD_SERVER_KEY }}
          port: 22
          script: cd /var/www/ && git clone https://github.com/bekachino/skynetEmployeeBonuses.git && cd skynetEmployeeBonuses && npm i && npm run build

      - name: Restart nginx
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 185.39.79.89
          username: beka
          key: ${{ secrets.DASHBOARD_SERVER_KEY }}
          port: 22
          script: sudo service nginx restart